### ISSUE TITLE
Module 00 -ex00 Welcome to SEA:ME

### ISSUE THREAD

**Issue by MicchelFAB** [SEAME-pt/SEAME-WarmUp-24-25#17]
## Exercise 00 : Welcome to SEA:ME

> Let’s explore the world of [SEA:ME](https://github.com/SEA-ME)!
* Follow this:
    1. Do you have a GitHub account? If not, create one.
    2. Fork [SEA:ME Students](https://github.com/SEAME-pt/SEA-ME-Students) from [SEA:ME-pt](https://github.com/SEA-ME-pt). Make sure you see all the branches!
    3. Clone forked repository
    4. Create a folder inside your cloned repo by the unique id generated as per following rule: 
        - If your full name is Jack Moon (FirstName: Jack, LastName: Moon), then your unique id would be jmoon (first letter of your first name followed by your lastname)
    5. Create a markup file by the same name as the folder: uniquename.md inside the folder
        - If your id is jmoon, then the file would be jmoon.md
    6. Fill in the information about yourself. (Use Template_Student_Bio.md file for reference):
    7. Save the changes.
    8. git add, git commit, git push
    9. Create a merge request (MR) to the MainJuly2024 branch in original repo of SEA:ME
    10. Do you know what you just did?

* Now for every project, remember to do following:
  - Fork the main project repo from SEA:ME
  - Work out and save all your work in the forked repo
  - Once done, provide us the links to your repo and evaluation form in your own [SEA:ME Students](https://github.com/SEA-ME/SEA-ME-Students) profile

**Comment by afmyhouse** [comment]
[comment]: # 

I don't have access to : 
[SEA-ME-Students](https://github.com/SEA-ME-pt/SEA-ME-Students)
